import sqlite3

conn = sqlite3.connect("accidentalidad.db")

cursor = conn.cursor()

_SQL = """
CREATE TABLE if not exists accidentes(
COD_DPTO TEXT,
COD_MUNIC TEXT,
A_DEFUN TEXT,
COD_INSP TEXT,
SIT_DEFUN TEXT,
OTRSITIODE TEXT,
COD_INST TEXT,
NOM_INST TEXT,
TIPO_DEFUN TEXT,
FECHA_DEF TEXT,
ANO TEXT,
MES TEXT,
HORA TEXT,
MINUTOS TEXT,
SEXO TEXT,
FECHA_NAC TEXT,
EST_CIVIL TEXT,
EDAD TEXT,
NIVEL_EDU TEXT,
ULTCURFAL TEXT,
MUERTEPORO TEXT,
SIMUERTEPO TEXT,
OCUPACION TEXT,
IDPERTET TEXT,
IDPUEBIN TEXT,
N_IDPUEBIN TEXT,
CODPRES TEXT,
CODPTORE TEXT,
CODMUNRE TEXT,
AREA_RES TEXT,
BARRIOFAL TEXT,
COD_LOCA TEXT,
CODIGO TEXT,
VEREDAFALL TEXT,
SEG_SOCIAL TEXT,
IDADMISALU TEXT,
IDCLASADMI TEXT,
PMAN_MUER TEXT,
CONS_EXP TEXT,
MU_PARTO TEXT,
T_PARTO TEXT,
TIPO_EMB TEXT,
T_GES TEXT,
PESO_NAC TEXT,
EDAD_MADRE TEXT,
N_HIJOSV TEXT,
N_HIJOSM TEXT,
EST_CIVM TEXT,
NIV_EDUM TEXT,
ULTCURMAD TEXT,
EMB_FAL TEXT,
EMB_SEM TEXT,
EMB_MES TEXT,
MAN_MUER TEXT,
COMOCUHEC TEXT,
CODOCUR TEXT,
CODMUNOC TEXT,
DIROCUHEC TEXT,
LOCALOCUHE TEXT,
C_MUERTE TEXT,
C_MUERTEB TEXT,
C_MUERTEC TEXT,
C_MUERTED TEXT,
C_MUERTEE TEXT,
ASIS_MED TEXT,
N_DIR1 TEXT,
T_DIR1 TEXT,
M_DIR1 TEXT,
C_DIR1 TEXT,
C_DIR12 TEXT,
N_ANT1 TEXT,
T_ANT1 TEXT,
M_ANT1 TEXT,
C_ANT1 TEXT,
C_ANT12 TEXT,
N_ANT2 TEXT,
T_ANT2 TEXT,
M_ANT2 TEXT,
C_ANT2 TEXT,
C_ANT22 TEXT,
N_ANT3 TEXT,
T_ANT3 TEXT,
M_ANT3 TEXT,
C_ANT3 TEXT,
C_ANT32 TEXT,
N_PAT1 TEXT,
T_PAT1 TEXT,
M_PAT1 TEXT,
C_PAT1 TEXT,
N_PAT2 TEXT,
C_PAT2 TEXT,
N_BAS1 TEXT,
C_BAS1 TEXT,
N_MCM1 TEXT,
C_MCM1 TEXT,
CAUSA_666 TEXT,
DD_EXP TEXT,
MM_EXP TEXT,
FECHA_EXP TEXT,
CAU_HOMOL TEXT,
GRU_ED1 TEXT,
GRU_ED2 TEXT,
HORA_SE TEXT);
"""

cursor.execute(_SQL)

with open("sql.sql", "r", encoding="UTF-8") as f:
    for i in f.read().split("\n"):
        cursor.execute(i)
        conn.commit()

# _SQL1 = """
#  SELECT count(*)
#  FROM accidentea
#  WHERE  = '';
# """

# cursor.execute(_SQL1)


# data = cursor.fetchall()

# for i in data:
#     print(i)